/// Print shell integration to stdout. Source it from your shell rc file:
///
///   eval "$(notez init zsh)"
///
/// The output handles things that have to live in the shell, not the binary —
/// most importantly `noglob` wrappers around write commands so messages can
/// contain `?` and `*` without zsh trying to glob-expand them.
pub fn run_init(shell: String) {
    match shell.to_lowercase().as_str() {
        "zsh" => print!("{}", zsh_init()),
        "bash" => print!("{}", bash_init()),
        "fish" => print!("{}", fish_init()),
        _ => {
            eprintln!("Unsupported shell: {}. Try: zsh, bash, fish", shell);
            std::process::exit(1);
        }
    }
}

fn zsh_init() -> &'static str {
    r#"# notez-cli shell integration (zsh)
# Generated by `notez init zsh` — eval this from your .zshrc.
#
# noglob wrappers: prevent zsh from expanding ? and * in unquoted args
# to write commands, so messages like `zlog did you fix the bug?` work.
alias zlog='noglob zlog'
alias znote='noglob znote'
"#
}

fn bash_init() -> &'static str {
    r#"# notez-cli shell integration (bash)
# Generated by `notez init bash` — eval this from your .bashrc.
#
# bash doesn't glob-expand ? and * the way zsh does in command args,
# so no wrappers are currently needed. This file is reserved for future
# integration hooks.
"#
}

fn fish_init() -> &'static str {
    r#"# notez-cli shell integration (fish)
# Generated by `notez init fish` — source this from your config.fish.
#
# fish doesn't glob-expand ? and * the way zsh does, so no wrappers are
# currently needed. This file is reserved for future integration hooks.
"#
}
